version: '3.8'

services:
  # 메인 애플리케이션
  app:
    image: ${NCP_REGISTRY_URL}/meme-wiki-be:latest
    container_name: meme-wiki-be
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - /home/ubuntu/logs:/app/logs
    labels:
      # Watchtower가 이 컨테이너를 모니터링하도록 설정
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Watchtower - 자동 이미지 업데이트
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/.docker/config.json:/config.json:ro
    environment:
      # Container Registry 인증 설정
      - WATCHTOWER_POLL_INTERVAL=300  # 5분마다 체크
      - WATCHTOWER_CLEANUP=true       # 이전 이미지 자동 정리
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_LABEL_ENABLE=true  # label로 지정된 컨테이너만 업데이트
      - WATCHTOWER_NOTIFICATIONS=shoutrrr://logger://
      - WATCHTOWER_NOTIFICATION_LOG_LEVEL=info
    labels:
      - "com.centurylinklabs.watchtower.enable=false"  # Watchtower 자신은 업데이트 안함
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 