spring:
  application:
    name: meme-wiki
  config:
    import: "optional:file:.env[.properties]"

  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 100

cloudflare:
  r2:
    access-key-id: ${CLOUDFLARE_R2_ACCESS_KEY_ID:}
    secret-access-key: ${CLOUDFLARE_R2_SECRET_ACCESS_KEY:}
    endpoint: ${CLOUDFLARE_R2_ENDPOINT:}
    bucket-name: ${CLOUDFLARE_R2_BUCKET_NAME:}

---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:core;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  sql:
    init:
      mode: never

---
spring.config.activate.on-profile: dev

spring:
  jpa:
    properties:
      hibernate:
        show_log: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://${DATABASE_HOST}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

---
spring.config.activate.on-profile: prod

spring:
  jpa:
    properties:
      hibernate:
        show_log: true
        format_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://${DATABASE_HOST}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

